copy *.pas %1
copy rtm.exe %1
copy dpmi16bi.ovl %1
copy hommx.txt %1
copy dudes.txt %1
copy hommxf.txt %1
copy geos.dat %1
copy combdefs.dat %1
copy monster.pic %1
copy font.pic %1
copy faces.pic %1
copy egavga.bgi %1
copy config.dat %1
copy dudes.exe %1
copy geoedit.exe %1
copy editcomb.exe %1
copy editface.exe %1
copy strings.dat %1
copy *.rmt %1
copy back.bat %1
